### ISSUE TITLE
Support importing wp_options data

### ISSUE THREAD

**Issue by cjmaio** [stenberg/content-staging#65]
It would be really nice (and unlike other similar solutions) if we could import data in the wp_options table. I think this would have to be something configurable, so it could be configured easily for other plugins. It would allow you to move over:
- Widgets
- Settings for Plugins
- Active Plugins (not sure how I feel about this one)
- Nav Menu Locations
- Other options for plugins (hence the configurable part)

**Comment by tokhi** [comment]
any updates on this issue?

**Comment by stenberg** [comment]
I think @phestermann was working on this around christmas. He might be able to provide you with more information.

**Comment by phestermann** [comment]
hi, I have been working on menu items. which is working now. guess I can add it the next day's. There are some changes related to the option white and blacklisting included. @stenberg maybe I create a pull request for that, would be good if you could have a brief look how the changes in the options might work with other installs.
