### ISSUE TITLE
Post/Taxonomy relationship broken on staging

### ISSUE THREAD

**Issue by cjmaio** [stenberg/content-staging#79]
When you stage a post with categories and tags, they do not relate to the post properly. It does properly create the taxonomies but does not relate them.

In my own fork, in a last ditch effort to just get it working so I could move a site over, I changed the following in `class-post-taxonomy-dao.php` on line 90 approximately...

```
protected function do_insert( Model $obj ) {
		//$data   = $this->create_array( $obj );
		//$format = $this->format();
		//$this->wpdb->insert( $this->get_table(), $data, $format );

		// TODO: Why does the above not work?
		wp_set_object_terms( $obj->get_post()->get_id(), $obj->get_taxonomy()->get_term()->get_slug(), $obj->get_taxonomy()->get_taxonomy(), true );
	}
```

As my comment suggests, I didn't have time to figure out what was wrong, which was more to do with wrapping my head around how it works. I'll continue to investigate and see if I can't track down the issue, but as an aside... why would we want to update the database directly rather than using the wp_set_object_terms function?

**Comment by cjmaio** [comment]
Okay, so that fix was lazy, and I figured out where the error was:

In the `$this->create_array()` function it creates an array, with one of the parameters being `term_order` ... when that's null, it just won't transfer over terms. Not sure if it's an issue in content staging, or my WordPress install...

My fix for it is in line 65 of `class-post-taxonomy.php`:

```
public function get_term_order() {
		return ( $this->term_order === null ) ? 0 : $this->term_order;
	}
```

**Comment by stenberg** [comment]
Great! Could you provide pull request for this fix?

**Comment by cjmaio** [comment]
Done!
